# Default values for omar-wms.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: omar-basemap

global:
  dockerRepository: nexus-docker-private-group.ossim.io
  imagePullSecret:
    registry: null
    username: null
    password: null

  createImagePullSecret: true
  useImagePullSecret: true
  createPVs: true

  volumes:
    basemap-data:
      type: ""
      nfsServer: null
      nfsMountPoint: null
      accessModes:
        - ReadOnlyOnce
      size: 1

  deployment:
    annotations: {}

  serviceAccount:
    enabled: false
    annotations: {}
    # name:

  envVars: {}

volumeNames:
  - basemap-data

# These variables can be overridden because of the use of the 'pluck' function:
# - createImagePullSecret
# - createHpa
# - createPVs

replicas: 1

livenessProbe:
  failureThreshold: 5
  initialDelaySeconds: 60
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 380

readinessProbe:
  failureThreshold: 15
  initialDelaySeconds: 30
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3
  path: /

resources:
  limits:
    cpu: 2000m
    memory: 1000Mi
  requests:
    cpu: 500m
    memory: 500Mi

image:
  name: omar-basemap
  tag: dev
  pullPolicy: IfNotPresent

internalPort: 8080
externalPort: 8080

terminationGracePeriodSeconds: 30

envVars:
  SPRING_CLOUD_CONFIG_LABEL: master
  JAVA_OPTS: "-server -Xms256m -XX:+UnlockExperimentalVMOptions -XX:MaxRAMFraction=1 -XX:+CMSClassUnloadingEnabled -XX:+UseGCOverheadLimit -Djava.awt.headless=true -XshowSettings:vm -Djava.security.egd=file:/dev/./urandom"

ossimDataLocalMountPath: /data

configmaps: {}

extraInitContainers: []

sideCars: []

deployment:
  annotations: {}

serviceAccount:
  # Specifies whether a service account should be created
  enabled: null
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and enabled is true, a name is generated using the fullname template
  # name:
