apiVersion: v1
kind: DeploymentConfig
metadata:
  name: omar-basemap
  namespace: omar-dev
  selfLink: /oapi/v1/namespaces/omar-dev/deploymentconfigs/omar-basemap
  uid: dc8f3fd2-82c2-11e7-ba3b-0e704fd9c8b2
  resourceVersion: '8869625'
  generation: 55
  creationTimestamp: '2017-08-16T20:38:29Z'
  labels:
    app: omar-openshift
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - omar-basemap
        from:
          kind: ImageStreamTag
          namespace: o2
          name: 'omar-basemap:latest'
        lastTriggeredImage: >-
          172.30.181.173:5000/o2/omar-basemap@sha256:4bb50d0105f2cb6e5915d4d1a0f95dfee118e8bfc3315d9329effd0d4b4f18ba
  replicas: 1
  test: false
  selector:
    app: omar-openshift
    deploymentconfig: omar-basemap
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: omar-openshift
        deploymentconfig: omar-basemap
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      volumes:
        - name: volume-basemap
          persistentVolumeClaim:
            claimName: basemap-dev-pvc
      containers:
        - name: omar-basemap
          image: >-
            172.30.181.173:5000/o2/omar-basemap@sha256:4bb50d0105f2cb6e5915d4d1a0f95dfee118e8bfc3315d9329effd0d4b4f18ba
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: volume-basemap
              mountPath: /data
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
status:
  latestVersion: 52
  observedGeneration: 55
  replicas: 1
  updatedReplicas: 1
  availableReplicas: 1
  unavailableReplicas: 0
  details:
    message: image change
    causes:
      - type: ImageChange
        imageTrigger:
          from:
            kind: ImageStreamTag
            namespace: o2
            name: 'omar-basemap:latest'
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2017-10-31T18:15:52Z'
      lastTransitionTime: '2017-10-31T18:15:52Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2017-11-30T14:30:32Z'
      lastTransitionTime: '2017-11-30T14:30:31Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "omar-basemap-52" successfully rolled out
  readyReplicas: 1
